### ISSUE TITLE
Второй шаг в обновлённой документации - ошибки

### ISSUE THREAD

**Issue by sxiii** [GolosChain/golosio-launching#5]
./start_full_node.sh
```
+ curl https://raw.githubusercontent.com/cyberway/cyberway.launch/master/genesis.json --output /var/lib/cyberway/genesis-data/genesis.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file 
Warning: /var/lib/cyberway/genesis-data/genesis.json: No such file or 
Warning: directory
 94  1455   94  1371    0     0  10465      0 --:--:-- --:--:-- --:--:-- 10465
curl: (23) Failed writing body (0 != 1371)
```

Потому что нету папки, соотв., однако, вот это:
```
mkdir -p /var/lib/cyberway/genesis-data/
```

тоже не помогает, т.к. скрипт всё равно удаляет эту директорию при запуске.

**Comment by sxiii** [comment]
Кроме того, если закомментировать функции удаления в env.sh, это тоже не помогает. Ошибка та же самая

**Comment by sxiii** [comment]
Update: создание этой директории не помогло, ошибка та же самая

**Comment by sxiii** [comment]
Дополнение: скрипт ./start_full_node.sh нужно запускать с правами суперпользователя, т.е. от root или с sudo ./start_full_node.sh. Этого нет в документации.

Ну и наконец, проверено:
* Скрипт не работает на Debian 10 (ошибка из этого issue)
* Равно как не работает на Fedora 33  (ошибка из этого issue)
* Равно как не работает на Ubuntu 20.04 и 18.04 (ошибки из другого issue)
* Равно как не работает на CentOS 7 (ошибки из другого issue)

**Comment by afalaleev** [comment]
> * Равно как не работает на Ubuntu 20.04 и 18.04 (ошибки из другого issue)
> * Равно как не работает на CentOS 7 (ошибки из другого issue)

Из какого issue? Можно ссылку?
Просьба ошибки связанные с запуском ноды CyberWay оставлять на https://github.com/cyberway/cyberway.launch

**Comment by afalaleev** [comment]
> Дополнение: скрипт ./start_full_node.sh нужно запускать с правами суперпользователя, т.е. от root или с sudo ./start_full_node.sh. Этого нет в документации.

В какой документации? 
В документации на https://github.com/cyberway/cyberway.launch указаны запуски с использованием sudo:
```sudo docker-compose up -t 120 -d```

**Comment by afalaleev** [comment]
> Кроме того, если закомментировать функции удаления в env.sh, это тоже не помогает. Ошибка та же самая

Ошибка с запуском `start_full_node.sh` исправлена в репозитории https://github.com/cyberway/cyberway.launch
Просьба ошибки по запуску ноды CyberWay оставлять в https://github.com/cyberway/cyberway.launch

**Comment by sxiii** [comment]
Да, ошибка исправилась, действительно. Спасибо!

Прошу прощения что issue не в том репо создал, формально т.к. следовал шагам из этого. Когда постил, сомневался ещё. Буду учитывать исходный репозиторий в будущем обязательно.
