### ISSUE TITLE
Не указаны требования для успешной сборки!

### ISSUE THREAD

**Issue by sxiii** [GolosChain/golosio-launching#6]
Добавить минимальные требования к ПО для запуска обоих реп

## Requirements
* Linux [...]
* Curl [v?], libcurl4, ...?
* Bash [v?]
* Git [v?]
* Docker 19.03.. [...]
* Что-то ещё?

**Comment by afalaleev** [comment]
Требовния для запуска полной ноды - https://github.com/cyberway/cyberway.launch

Стандратные версии, так как особых флагов не используется:
- bash
- curl
- fold
- head
- tail 
- df
- sed
- grep
- tar
- sudo 

Обязательные требования: 
- git (проверялось на v2.7, для работы нужна версия достаточная для работы с github) 
- docker v19.03
- docker-compose v2.1

**Comment by sxiii** [comment]
Вот это супер! Спасибо!

**Comment by sxiii** [comment]
Открыл повторно т.к. этой информации по прежнему нет в документации

**Comment by afalaleev** [comment]
> Открыл повторно т.к. этой информации по прежнему нет в документации

Этот репозиторий - он для запуска микросервисов golos io
В какую документацию и что нужно добавить?

**Comment by afalaleev** [comment]
Закрыл issue, так как он не имеет отношения к сервисам golos io

**Comment by sxiii** [comment]
Хмм, нода кибервея необходима для функционирования сервисов Golos.io -> как это "не имеет отношения"? Самое что ни на есть прямое.

Кроме того, у самого golosio-launching нет зависимостей? Это самодостаточный репозиторий? Зависимости указывать желательно всегда, и максимально подробно, это же никому не повредит.

Зависимости не указаны ни в этом репозитории, ни в Cyberway.
